version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "mercury-test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
  # nodejs:
  #   build: .
  #   volumes: 
  #     - ./:/app
  #     - /app/node_modules
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     - zookeeper
  #     - kafka
  #   links:
  #     - zookeeper
  #     - kafka
  #   environment:
  #     BROKER_1: kafka:9092
  #   networks:
  #     - default
networks:
  default:
